// This file was auto-generated by graphql-fragment-codegen. Do not edit it by hand.

export const File = `fragment File on File {
  
}
`

export const Subscription = `fragment Subscription on Subscription {
  onData {
    id
    data
  }
}
`

export const SubscriptionResult = `fragment SubscriptionResult on SubscriptionResult {
  id
  data
}
`
